# Generated by Django 3.1.2 on 2021-02-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('tweet_text', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positif', models.IntegerField(default=0)),
                ('negatif', models.IntegerField(default=0)),
                ('netral', models.IntegerField(default=0)),
                ('history', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history_sentimen', to='sentimen.history')),
            ],
        ),
    ]
